version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "11:00"
    open-pull-requests-limit: 10
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "11:00"
    open-pull-requests-limit: 10
    reviewers:
      - Wondertan
      - renaynay
    labels:
      - kind:deps
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "11:00"
    open-pull-requests-limit: 10
